# START FROM ASWF PLATFORM 2022
FROM aswf/ci-base:2024
RUN mkdir -p /app/Release
WORKDIR /app
COPY ./* .

RUN cmake -S ./etc/SuperBuild -B Release -DCMAKE_INSTALL_PREFIX=$PWD/Release/install -DCMAKE_PREFIX_PATH=$PWD/Release/install -DCMAKE_BUILD_TYPE=Release
RUN cmake --build Release -j 4 --config Release

RUN mkdir -p ./releases/tlRender-linux-rocky8/bin
RUN ln -s ./releases/tlRender/src/tlRender-build/bin/tlbake/tlbake ./releases/tlRender-linux-rocky8/bin/tlbake
RUN ln -s ./releases/tlRender/src/tlRender-build/bin/tlplay/tlplay ./releases/tlRender-linux-rocky8/bin/tlplay
RUN ln -s ./releases/install ./releases/tlRender-linux-rocky8/install

# tlbake
RUN echo "SCRIPT=$(realpath "$0")" > ./releases/tlRender-linux-rocky8/tlbake_run.sh
RUN echo "SCRIPTPATH=$(dirname "$SCRIPT")" > ./releases/tlRender-linux-rocky8/tlbake_run.sh
RUN echo "export LD_LIBRARY_PATH=$SCRIPTPATH/install/lib:$LD_LIBRARY_PATH" > ./releases/tlRender-linux-rocky8/tlbake_run.sh
RUN echo "$SCRIPTPATH/tlbake" > ./releases/tlRender-linux-rocky8/tlbake_run.sh

# tlbake
RUN echo "SCRIPT=$(realpath "$0")" > ./releases/tlRender-linux-rocky8/tlplay_run.sh
RUN echo "SCRIPTPATH=$(dirname "$SCRIPT")" > ./releases/tlRender-linux-rocky8/tlplay_run.sh
RUN echo "export LD_LIBRARY_PATH=$SCRIPTPATH/install/lib:$LD_LIBRARY_PATH" > ./releases/tlRender-linux-rocky8/tlplay_run.sh
RUN echo "$SCRIPTPATH/tlplay" > ./releases/tlRender-linux-rocky8/tlbake_run.sh

RUN zip -r ./releases/tlRender-linux-rocky8.zip ./releases/tlRender-linux-rocky8/
